added builtin_env
Ray-cmd/minishell pull request #43
Opened 2023-10-12 23:11 UTC by FizzYxWizzY

used "ctx->grpvar->global->num_elements" to determinate where the env list stops otherwise it segfaulted.

2023-10-13 07:31 UTC, Ray-cmd requested changes
Si tu a envie de faire le wrapper `grpvar_show()` sur l'exemple de `grpvar_has()`, tu peux, sinon, utilise simplement `lstvar_show()`

2023-10-13 07:31 UTC, Ray-cmd commented on builtins/env.c
> +		return (1);
Tu peux utiliser la fonction `lstvar_show()` pour afficher toute les variables sans te prendre la tête avec une boucle et sans avoir a check les sf.

C'est my bad, j'ai oublier de faire un wrapper `grpvar_show()`:

```c
lstvar_show(ctx->grpvar->global);
```

Sauf erreur, l'affichage se fait correctement en mode `name=value`.

2023-10-14 11:26 UTC, Ray-cmd requested changes
Change juste le fd pour le message d'erreur est c'est tout bon !

2023-10-14 11:26 UTC, Ray-cmd commented on builtins/env.c
> +		printf("env: '%s': Permission denied\n", argv[1]);
Pour les messages d'erreurs, faut utiliser `ft_putstr_fd()` car le message doit être inscrit sur la sortie d'erreur (fd 2).

Et je ne comprend pas la logique pour ce message d'erreur. Quand je test chez moi avec Bash, j'ai deux message différent en fonction de la situation.

Exemple : j'ai un dossier `test` dans mon dossier courant. Si je fait `env  test` j'ai le message `env: ‘test’: No such file or directory`, et si je fait `env test/` j'ai le message `env: ‘test/’: Permission denied`.

Je sais pas à quel point c'est un risque pour l'évaluation de pas avoir un message d'erreur accurate par rapport à `env` de Bash. Faut aller check dans les screenshots de la marche à suivre de l'éval pour voir si c'est un truc qui est demandé ou pas.

Pour moi je m'en balek du message, donc juste changer le fd d'affichage et on est good.

Le restes des erreurs est vraiment gérer à la zeub dans le reste du projet, faudra sûrement réfléchir pour voir comment on peu rendre le truc homogène.

2023-11-01 19:39 UTC, FizzYxWizzY commented
voilou, pas 100% sur de la behavior du env enfaite...

2023-11-01 20:39 UTC, Ray-cmd approved these changes
Tout bon

2023-11-01 20:39 UTC, merged